[package]
name = "ntscrs-cbind"
version = "0.1.0"
edition = "2018"

[dependencies]
ntscrs = { git = "https://github.com/valadaptive/ntsc-rs.git" }

[lib]
name = "ntscrs_cbind"
crate-type = ["staticlib"]

[build]
rustflags = ["-C", "target-cpu=native"]